
server:
  port: 9005
spring:
  application:
    name: loans
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa-microservice-loans
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"